# Generated by Django 4.2 on 2024-07-07 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 6, 9, 5, 26, 535561, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
