# Generated by Django 4.2.12 on 2024-07-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_invoice_state'),
        ('sales', '0003_alter_invoice_state'),
    ]

    operations = [
    ]
