# Generated by Django 4.2.12 on 2024-07-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_merge_20240722_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
